### ISSUE TITLE
Why a fork for package-server-sync?

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/organization#17]
I have not seen any discussion about [`peerlibrary:meteor-packages`](https://github.com/peerlibrary/meteor-packages) being moved to this organization, but I see a fork here: https://github.com/Meteor-Community-Packages/package-server-sync

So, I do not think anyone really asked me (I made that package) if they could take over maintenance, or even make a MR against it. So not sure why forking a package instead of taking it over? So if somebody wants to take it over, please ask. No need to duplicate packages unnecessary.

Also, if people prefer, I can move some of packages from `peerlibrary` to here as well. But that is a separate discussion.

cc @copleykj

**Comment by copleykj** [comment]
Hey @mitar. Sorry, there wasn't any discussion around this. I initially started modifying the package as part of my work to build a replacement for Atmosphere. I started to get busy and rather than keeping the changes local, and risk losing if something unexpected happened, I created a new repo here and pushed them up.

If you are willing to make the move, I'd be more than happy to shuffle things around and make that happen.

**Comment by mitar** [comment]
I can add you to that repository and add permissions for you to publish `peerlibrary:meteor-packages`? What is your Meteor username?

**Comment by copleykj** [comment]
Username is the same as here. Did you want to transfer the repo to this org, or keep ownership?

**Comment by mitar** [comment]
I would keep ownership, but transfer it here.

**Comment by mitar** [comment]
Moved: https://github.com/Meteor-Community-Packages/meteor-packages

**Comment by mitar** [comment]
Also published the latest version as `peerlibrary:meteor-packages@1.0.0`.

And added permissions for you so that you can publish the package under that name.
