### ISSUE TITLE
New package for inclusion - simple-schema-js

### ISSUE THREAD

**Issue by harryadelb** [Meteor-Community-Packages/organization#28]
## Links
* [Github repository](https://github.com/aldeed/simple-schema-js)
* [NPM](https://www.npmjs.com/package/simpl-schema)

## Current status of the project
 * Abandoned

 ## Reasoning
 
It can be used with [validated methods](https://github.com/meteor/validated-method), [collection2](https://github.com/aldeed/meteor-collection2) and [uniforms](https://github.com/vazco/uniforms/). 

 ## Progress
 - [ ] Discussion finished
 - [ ] Moved / Forked
 - [ ] Team Created
 - [ ] Meteor Org Created and set as maintainer
 - [ ] `communitypackages` org added as a maintainer on Atmosphere

cc @aldeed

**Comment by sebakerckhof** [comment]
Is it abandoned? Last commit on the npm package was yesterday.

**Comment by harryadelb** [comment]
@sebakerckhof I understand it's really not, but there was no option for "unmaintained"! 
@aldeed has made it clear that he doesn't have much time any more and willing to transfer them to the organization. And the repository isn't as active as it used to be.
>Thanks for getting this started. I definitely have a few Meteor packages that I don't have much time for anymore. Happy to transfer them.

https://github.com/Meteor-Community-Packages/organization/issues/1#issuecomment-471703020

**Comment by StorytellerCZ** [comment]
If @aldeed is fine with it, I think there is going to be enough willing maintainers as this and #29 are heavily used packages.

**Comment by harryadelb** [comment]
@StorytellerCZ 
>are heavily used packages
Exactly, and that's why they need to be of our top priority.

**Comment by harryadelb** [comment]
I emailed him. :crossed_fingers:

**Comment by harryadelb** [comment]
Does anybody know of other ways we can contact @aldeed ? BTW, I emailed him at aldeed@gmail.com.

**Comment by aldeed** [comment]
Sorry I haven't had time to deal with this until now. Since I do still use SimpleSchema NPM, it isn't abandoned as much as some others. I usually go through the issues and PRs a few times a year. I would likely transfer it if people want, but it isn't a Meteor-specific package anymore so I don't know if it fits the criteria.

The older https://github.com/aldeed/meteor-simple-schema, on the other hand, is completely abandoned so I would transfer that if anyone is still using it and wants to maintain it.

**Comment by harryadelb** [comment]
@aldeed If you still maintain the NPM version, I think there's no need to transfer it to the organization. The less packages for the organization to maintain the better. Sorry, for jumping the gun. 

What do you guys think?
cc @copleykj @StorytellerCZ @sebakerckhof

**Comment by copleykj** [comment]
@harryadelb I'm with you on this. I think since @aldeed is still actively working on the package, and since it's not Meteor specific, we don't need to move forward. If at some point it wasn't maintained, then I would say it might be a candidate since it does integrate with several other Meteor packages very well.

As far as the meteor specific version of the package, I don't see any reason since it doesn't offer anything above or beyond the NPM version.

**Comment by coagmano** [comment]
I'm thinking it might be better to share maintainership, at least so simple bugs that break out-of-the-box meteor compatibility like aldeed/simple-schema-js#347 can be fixed in a timely manner.

It kinda sucks that right now the npm package officially recommended by the guide requires extra configuration to work in Meteor > 1.8 and doesn't work at all for < 1.8
Especially when the fix is one line of babel config and a re-publish

**Comment by copleykj** [comment]
@coagmano I'm with you on this.

Also, if a package is transferred here but the author still wants to have an active role that would be absolutely fantastic.

I consider Simple-Schema and Collection2 to be 2 of the most important packages to the Meteor ecosystem, and so I think we should strive at the very least for timely critical bug fix releases.

cc @aldeed

**Comment by SimonSimCity** [comment]
@copleykj I agree with you on `collection2`, but am not so convinced in calling `simpl-schema` a definite must for Meteor projects. I had to fix it to `1.4.2` because of https://github.com/aldeed/simple-schema-js/issues/257 and am now in the scout for other packages, able to replace it - at least when verifying meteor-methods.

**Comment by copleykj** [comment]
@SimonSimCity isn't `simpl-schema` an integral part of `collection2`? I understand your frustration with code that worked a certain way at one point, but no longer works that way. We can't let something like that dictate whether it's an important part of the ecosystem though. Eric has expressed his willingness to restore this functionality if fixed in a way that doesn't reintroduce issues.

**Comment by aldeed** [comment]
OK with me to close this. If anybody is interested in helping maintain it let me know. I've updated it to auto-release based on conventional commits now, so it should be fairly easy to keep fixes moving through.
