### ISSUE TITLE
New package for inclusion - vsivsi:file-collection

### ISSUE THREAD

**Issue by edemaine** [Meteor-Community-Packages/organization#33]
## Package/project name & description
file-collection enables arbitrary-size binary file support using MongoDB gridFS, so users can easily upload/download files in a Meteor system, keeping everything in the MongoDB.

Major features from the README:
* HTTP upload and download including support for Meteor authentication
* Client and Server integration of resumable.js for robust chunked uploading
* Also compatible with traditional HTTP POST or PUT file uploading
* HTTP range requests support random access for resumable downloads, media seeking, etc.
* Robust file locking allows safe replacement and removal of files even on a busy server
* External changes to the underlying file store automatically synchronize with the Meteor collection
* Designed for efficient handling of millions of small files as well as huge files 10GB and above

## Links
* [Atmosphere](http://atmospherejs.com/vsivsi/file-collection)
* [Github repository](https://github.com/vsivsi/meteor-file-collection/)

## Current status of the project
 * Abandoned / [maintenance mode](https://github.com/vsivsi/meteor-file-collection/#notice)
 * I (@edemaine) have a fork that runs on the current version of Meteor ([Atmosphere](https://atmospherejs.com/edemaine/file-collection), [Github](https://github.com/edemaine/meteor-file-collection)), but it was a quick fix and doesn't address existing PRs etc.

 ## Reasoning
Storing all files in MongoDB makes it particularly easy to backup the state of a Meteor project: just backup the database.

I use the package in my [Coauthor](https://github.com/edemaine/coauthor/) system, so it's important to me.  I'm willing to maintain it for now, at least trying to review PRs and I have some (slow) plans to improve some functionality.  This has been discussed some on https://github.com/vsivsi/meteor-file-collection/pull/172, with support from the original author, @vsivsi.
 
 ## Progress
 - [ ] Discussion finished
 - [ ] Moved / Forked
 - [ ] Team Created
 - [ ] Meteor Org Created and set as maintainer
 - [ ] `communitypackages` org added as a maintainer on Atmosphere

## Related projects
* [vsivsi:job-collection](https://github.com/Meteor-Community-Packages/organization/issues/30)

**Comment by juliomac** [comment]
Thanks for reopening it.

This Package has been installed almost 12.000 times. It is the only package that allows using gridFS for file storage (pictures and movies) in an easy and secure way after the demise of the complex fs:collection. The alternative [https://github.com/VeliovGroup/Meteor-Files](url) is not as an elegant solution for grids as this one is.

It is so popular that It has already been forked many times to replace the older coffescript dependency, like done here [https://github.com/brucejo75/meteor-file-collection](url) and here with an non-coffee version [https://github.com/swiftcourt/meteor-file-collection](url) .

The other problem is its incompatibility with SSL mongo servers, which is an impediment for using Mongo Atlas, for instance, as detailed here [https://forums.meteor.com/t/issues-migrating-from-mlab-to-atlas/54206](url) that were supposedly solved here [https://github.com/sakeena12/meteor-file-collection](url) .

**Comment by edemaine** [comment]
Just glancing, @sakeena12's https://github.com/sakeena12/meteor-file-collection does look like a good starting point, incorporating @brucejo75's CoffeeScript upgrade and `mongoOptions` passthrough. Are either you interested in helping maintain this project?

**Comment by juliomac** [comment]
Hi @edemaine, I don't feel I have enough knowledge to take on this task, specially regarding CoffeeScript.

**Comment by brucejo75** [comment]
Hi @edmaine,


For basic Mongo file storage.  I don't recommend this package, it is designed for very large files and able to handle interrupted streams, etc.  This is way overkill for simple storage of files.   I had used `vsivsi:file-collection` originally as I was beginning to understand Meteor and it was really the only working Mongo file package at the time.

I ended up switching to a more modern technique simply using [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), [express](https://www.npmjs.com/package/express) & Mongo [GridFSBucket](http://mongodb.github.io/node-mongodb-native/3.1/api/GridFSBucket.html).  It turned out the code to integrate was vastly simplified compared to `vsivsi:file-collection`.

-Bruce

**Comment by juliomac** [comment]
> Hi @edmaine,
> 
> For basic Mongo file storage I don't recommend this package. `vsivsi:file-collection` is designed for very large files and able to handle interrupted streams, etc. This is way overkill for simple storage of files. I had used `vsivsi:file-collection` originally as I was beginning to understand Meteor and it was really the only working Mongo file package at the time.
> 
> I ended up switching to a more modern technique simply using [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), [express](https://www.npmjs.com/package/express) & Mongo [GridFSBucket](http://mongodb.github.io/node-mongodb-native/3.1/api/GridFSBucket.html). It turned out the code to integrate was vastly simplified compared to `vsivsi:file-collection`.
> 
> -Bruce

How have you done it? Have you got any code example that I could reuse and also replace `vsivsi:file-collection` for good in my code? My goal is to continue using Mongo for saving small pictures in database.

**Comment by brucejo75** [comment]
## Client Side
1. In HTML you will want an [`<input type="file" id="yourID"...>`](https://www.w3schools.com/tags/tag_input.asp) tag.
2. Create a meteor event handler on input change e.g. for Blaze [`'change #yourID': function fileInputChanged(event, template)`](http://blazejs.org/api/templates.html#Template-events)...
3. In your event handler you will do the file upload. Read up on [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).  On the client you can use it to `POST` or `PUT` a file request against a REST interface on your server.
5. It would be good to be familiar with [`async`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) functions.

## Server Side
1. You can use [`express`](https://www.npmjs.com/package/express) to process the incoming [REST](https://www.google.com/search?hl=&site=&q=express+rest) request.
2. Include the [mongo](https://atmospherejs.com/meteor/mongo#direct-access-to-npm-mongodb-api) package so that you can get access to `MongoInternals`.
3. In your express handler you can then access [`GridFSBucket`](http://mongodb.github.io/node-mongodb-native/3.1/api/GridFSBucket.html) via `MongoInternals`.
4. Read up on [node streams](https://nodejs.org/api/stream.html). Once you have a GridFS interface you can then pipe the incoming file to a [`GridFSBucket` upload stream](http://mongodb.github.io/node-mongodb-native/3.1/api/GridFSBucket.html#openUploadStreamWithId).

## Summary of main parts
- an input form that you can browse to a file to upload.
- When you choose the file it will fire your event handler.
- In the handler you send off a REST url request.
- In the server express handler you receive the REST url request.
- Then you engage Mongo's `GridFSBucket` to pipe the file stream directly into the Mongo DB `fs.files` collection.

**Comment by juliomac** [comment]
Great! I will try that!

**Comment by juliomac** [comment]
> 1. You can use [`express`](https://www.npmjs.com/package/express) to process the incoming [REST](https://www.google.com/search?hl=&site=&q=express+rest) request.

Hi @brucejo75 , I am trying this in practice, but you are suggesting using Express framework inside Meteor framework just for the process of REST? Could we just use Meteor's own REST processing `HTTP` method [https://docs.meteor.com/api/http.html](url) or `simple:rest` package ?

**Comment by brucejo75** [comment]
@juliomac,

1. Express framework is for the server side to process the incoming packets.  [`HTTP`](https://docs.meteor.com/api/http.html) does not handle incoming packets.  `simple:rest` looks like it has the capability to define REST routes, so you could use that.  I recommend [`express`](https://www.npmjs.com/package/express), pretty standard, quite powerful for handling authentication, errors, etc..
2. [`HTTP`](https://docs.meteor.com/api/http.html) could be used instead of `fetch()` on the client side.  I use `fetch()` because it is a standard browser feature now and the code is pretty simple.

**Comment by edemaine** [comment]
Meteor's [webapp](https://docs.meteor.com/packages/webapp.html) package ought to suffice. That's what vsivsi:file-collection uses, and I've also used it for other file access in other projects.

I personally would not use Meteor and Express together. I'd rather have a project that's easy to install with minimal dependencies, and Meteor should support everything you need out of the box. (I could see switching wholesale to Express, but I wouldn't.) But maybe that's just me...

Anyway, this thread doesn't seem like the place to discuss, unless @brucejo75 is suggesting that vsivsi:file-collection should not be added to Meteor Community Packages?

For what it's worth, I still use vsivsi:file-collection everyday in a major project, and am still willing to help maintain it.

**Comment by brucejo75** [comment]
Thanks @edmaine,

- Yes, I am recommending to not maintain this package.  Unless your usage is for multi-GB streaming files this package is harder to use, has a ton of overhead and not much benefit. Also, `coffescript` - yuck.

-  Any of the packages recommended `simple:rest` or `webapp` should work fine.

**Note:** I wouldn't be too afraid to install NPM packages directly.  You can see that [`webapp`](https://github.com/meteor/meteor/blob/devel/packages/webapp/package.js#L6-L15) depends on a number of npm packages.  Notably [`connect`](https://www.npmjs.com/package/connect).  It looks like express used to depend on connect but they removed that dependency.  You can also see that connect has been in light maintenance mode for the last couple of years.  I think express is the preferred solution these days.

Even though you are using "Meteor" packages they can pull in npm dependencies.

**Comment by edemaine** [comment]
@brucejo75 I'm not afraid to install NPM packages. But I don't want to run two Node.js server processes (Meteor and Express) for a single project. Unless there's some integration that lets Express apply its hooks from within Meteor (via `webapp`) or vice versa?

What is the extra overhead of vsivsi:file-collection? The Files subscription?

In my application, I do routinely upload and download 1-100MB files.  And you are welcome to your opinion about CoffeeScript, but it's still my preferred language for all projects, so that's actually a positive for me.

**Comment by brucejo75** [comment]
Hi @edmaine,

Oh, you don't need 2 servers.  Simply [`npm install express`](https://guide.meteor.com/using-npm-packages.html) into your Meteor server.  Then start using the api in your Meteor server code.  I think of Meteor as nothing more than some `API sugar` on top of node.  Sure it uses `websockets` for DDP & methods.  But you can still define `http` endpoints via your favorite package. 

If you look closely at `webapp` it does exactly that with the `connect` package.

**Summary:** At its core a Meteor server is simply a node server.  And this is a great thing about Meteor, you do not have to use it at all if you choose not to.  Very flexible.

It all works together in one server.

### Benefits without vsivsi:file-collection
When I removed `vsivsi:file-collection` I got 3 benefits:
1. Integrating my file upload as I described above was more straightforward and required less code for me than integrating with `vsivsi:file-collection`.
2. I no longer have the `vsivsi:file-collection` code in my app.
3. No more `coffeescript` compiler incompatibilities.

3 big wins.

Sorry for the `coffeescript` crack earlier.  I know some people love it but introduces maintenance & sharing headaches because `coffeescript` is not widely adopted and it is another toolset that can introduce incompatibilities.

**Comment by juliomac** [comment]
> 1. Integrating my file upload as I described above was more straightforward and required less code for me than integrating with `vsivsi:file-collection`.

Interesting... I would think adding an entire framework like `express` would add a lot more code than using a single  package.

**Comment by brucejo75** [comment]
@juliomac,

Good thought.  But the problem is that `vsivsi:file-collection` includes [`express`](https://github.com/vsivsi/meteor-file-collection/blob/master/package.js#L23) in addition to other packages and its own code.

And look at all the other [packages ](https://github.com/vsivsi/meteor-file-collection/blob/master/package.js#L29)that `vsivsi:file-collection` depends on and therefore pulls in.

And interestingly, `vsivsi:file-collection` also includes `webapp` which pulls in [`connect`](https://github.com/meteor/meteor/blob/devel/packages/webapp/package.js#L8) which is the precursor to express (express was originally built on connect).

With `vsivsi:file-collection` you essentially get 2 copies of express plus a bunch of other packages.

**Comment by juliomac** [comment]
@brucejo75 , thanks for the great analysis on this package. I would never know that it was using `express` behind the scenes and that it was so heavy.

I think you have put out the last argument against the package. I would definitely follow your advice.

If I succeed, I will post here my experiences with the suggested path.

Thanks!
