### ISSUE TITLE
New package for inclusion - AutoForm

### ISSUE THREAD

**Issue by pouya-eghbali** [Meteor-Community-Packages/organization#43]
## Package/project name & description

AutoForm is a Meteor package that adds UI components and helpers to easily create basic forms with automatic insert and update events, and automatic reactive validation.

## Links
* [Atmosphere](https://atmospherejs.com/aldeed/autoform)
* [Github repository](https://github.com/aldeed/meteor-autoform)
* [Project homepage](https://atmospherejs.com/aldeed/autoform)

## Current status of the project

 * Abandoned

 ## Reasoning

This package has a lot of users (199.9k installs on atmosphere) and it is abandoned. It has 530 github issues, and 23 pull requests. It does not have any alternatives as far as I know. I forked this project, did a lot of performance enhancements and bug fixes, and I'm planning to maintain this package at least for a few years.
 
 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by copleykj** [comment]
Does anyone else want to weigh in on this? I tend towards shying away from blaze specific packages unless commitment too maintaining Blaze manifests.

**Comment by guncebektas** [comment]
One of the most important packages for the blaze and I'm really happy to see the improvements on it.

**Comment by harryadelb** [comment]
I believe the main focus of the organization is to maintain the ultra vital packages important to the community which are currently abandoned/unmaintained.
It's important not just to add packages to the organization but also finding those who are willing to maintain them. With that being said, if you are willing to do this on your own, what value is attained from putting this package under the organization? aside from publicity?  

>I'm planning to maintain this package at least for a few years

**Comment by vparpoil** [comment]
In my mind, being moved under this organization allows 2 things:

- limit the number of forks available outside and hence provide better quality package

- prevent the package from being abandoned again in the future with no one that can step in to work on it (since the organization is granted access)

**Comment by pouya-eghbali** [comment]
> limit the number of forks available outside and hence provide better quality package

Quoting from meteor forums:

> You should coordinate with the meteor community packages project though so there aren’t multiple versions of these

That's the main reason for me. A lot of us depend on this package, some of us forked it and made some modifications and bug fixes, it would be nice to have all these in one place.

I heavily depend on this package. I have form builders, dynamic schemas, rules and etc that are based on autoform. I will continue working on autoform for a few years and I want to share the modifications with the community, whether in MCP or outside MCP.

**Comment by jankapunkt** [comment]
Heavy autoform user here. If there is a clear roadmap for fixes and senseful features (remove underscore etc., allow custom schema validator besides simpleschema, etc.) I am all in for contribution.

**Comment by pouya-eghbali** [comment]
> Heavy autoform user here. If there is a clear roadmap for fixes and senseful features (remove underscore etc., allow custom schema validator besides simpleschema, etc.) I am all in for contribution.

Removing underscore is a good idea, it'll help with performance and code quality, and it'll make it easier to maintain the code.

I have some issues with simpleschema, specially the `clean` method, is really slow, but for now I won't be able to help with that. My focus is more on bug fixes and performance, once we accomplish that goal and have a clean code we can make a release and start adding features.

**Comment by jankapunkt** [comment]
Agree. Count me in on the maintainer team.

**Comment by StorytellerCZ** [comment]
If we are going to do this, then I suggest that we start a Blaze team under which will be all primarily Blaze packages. If needed this team can then can create sub-teams.
In general, now that people are volunteering, I'm for including this package. Though I don't use this package so I don't have time to support this effort beyond organizational help.

**Comment by pouya-eghbali** [comment]
@jankapunkt I have started the process of removing underscore. @StorytellerCZ I agree with a Blaze team. I started my project with Meteor 0.6, Blaze was the obvious choice back then, I have a lot of Blaze specific code and I'll contribute any enhancements and bug fixes I make.

**Comment by jankapunkt** [comment]
If you want you can add me to the Blaze group. I am also working with Blaze since 1.2 but kept the projects always updated until 1.8.2 and I won't move to other engines for these projects.

@pouya-eghbali where do you work on this? The original or a fork? I think @aldeed has a longer response time so question is, if we just work on a fork and just wait for atmosphere group add or on the original and wait for it to be transfered?

**Comment by pouya-eghbali** [comment]
This is my fork:

https://github.com/pouya-eghbali/meteor-autoform

I completely detached the fork from original repo, for many reasons.

**Comment by guncebektas** [comment]
I'm also using blaze from 1.2 and happy with it. All our projects are up to date (1.8.1). You can add me to the group. I will be happy to help.

**Comment by pouya-eghbali** [comment]
I use latest release-1.9 branch of Meteor (custom dev_tools with node 13 on FreeBSD). I kept upgrading my project, packages and dependencies, and forked a few unmaintained packages that didn't work on newer versions of Meteor.

Underscore is gone @jankapunkt.

When, how and where should we (In case we all agree we should) start the Blaze team? I'm going to move my Meteor works (tools, scripts, forked packages, new packages, etc) all under one organization soon. I'll move to MCP any of these that MCP is interested in.

**Comment by StorytellerCZ** [comment]
OK, no matter what I'll get the Blaze team started. @jankapunkt @guncebektas and @pouya-eghbali I'll set you as the initial members.

**Comment by aldeed** [comment]
I would be fine with transferring the main repo and package if that's what people want. Although I kind of try to keep it working and look at it at least once a year, I don't use it anymore so it's hard to know how best to fix issues or in what direction to go with enhancements.

If there's a fork that more people are using and it makes more sense to move that, I'm fine with that, too. I could update the original to redirect people to the fork.

I have a number of related repos that I don't maintain. I have no idea how widely used these are, but if there's interest in moving any of these to community org, let me know.

https://github.com/aldeed/meteor-cfs-autoform
https://github.com/aldeed/meteor-autoform-bs-datetimepicker
https://github.com/aldeed/meteor-autoform-select2
https://github.com/aldeed/meteor-autoform-bs-button-group-input
https://github.com/aldeed/meteor-autoform-bs-datepicker

Otherwise I would probably archive them.

There is also https://github.com/aldeed/autoform-demo, which is still hosted at http://autoform.meteorapp.com/ through a special Galaxy account that MDG gave me. It would make sense to either transfer that or shut it down and have new maintainers spin up a different demo site.

**Comment by jankapunkt** [comment]
I suggest to transfer the original and merge the improvements from the forks. @pouya-eghbali already did some great improvements there.

I could keep track of the extensions, since I wrote so many extensions for AF and feel pretty comfortable there.

Regarding the Galaxy account - It is also possible to host DEMOs on Github (as long as they are client-side only) using [frozeman/meteor-build-client](https://github.com/frozeman/meteor-build-client). Unless you include routes it works pretty well.

**Comment by pouya-eghbali** [comment]
I'm a little busy these days but I tried my best to fix the issues reported in the past few days.

@aldeed I made a lot of optimizations to your package, some of the changes are huge but I tried to keep compatibility. Right now I'm fixing the issues caused by these optimizations. I was planning to fix all these kind of issues, modernize the code (I've already removed the underscore dependency) and then rename the package and make a release. But it would be nice to keep the package name and make a 7.0.0 release instead.

**Comment by aldeed** [comment]
OK I will plan to transfer all the autoform repos later this week if no objections, and grant permissions on the Meteor pkgs. I'll take down the hosted demo site. Sounds like it would need to be rewritten for 7.0 changes soon anyway.

**Comment by harryadelb** [comment]
Any update on this?

**Comment by jankapunkt** [comment]
Friendly ping :-) I think @pouya-eghbali already did a great improvement towards a 7.0 release and might just need to merge, once transfered. :rocket:

**Comment by pouya-eghbali** [comment]
I'm ready to transfer my fork (or the changes the community wants), however, I have no clue what's the next step. I'm still working on the fork, doing bug fixes as I find them and trying to improve the performance.

**Comment by jankapunkt** [comment]
The thing is, that @aldeed needs to add  communitypackages as a maintainer on Atmosphere so you can publish your 7.0 under `aldeed:autoform`

**Comment by copleykj** [comment]
Looks like repos are being transferred over.

**Comment by aldeed** [comment]
Indeed 😄 

Sorry for the long delay. Seems to be the usual these days, but things do get done eventually.

Transferred to `Meteor-Community-Packages` and added `communitypackages` as maintainer:
- https://github.com/aldeed/meteor-autoform
- https://github.com/aldeed/meteor-autoform-bs-datepicker
- https://github.com/aldeed/meteor-autoform-bs-datetimepicker
- https://github.com/aldeed/meteor-autoform-select2
- https://github.com/aldeed/meteor-autoform-bs-button-group-input

Archived, not transferred:
- https://github.com/aldeed/meteor-cfs-autoform
- https://github.com/aldeed/autoform-demo

@pouya-eghbali @jankapunkt If you need me to do anything else, let me know.

**Comment by copleykj** [comment]
No apology necessary. Delays are to be expected in open source :smiley:

**Comment by pouya-eghbali** [comment]
Awesome! I'm actively working on my AutoForm fork as I'm using it in an ERP. My plan was to do some bug fixes and performance enhancements, I believe we should keep it like that for a while and only do bug fixes, make it clean and keep it maintained.

There's a lot we can do, I've already removed underscore dependency but there's still a lot of code that can be refactored or can be converted to ES6.

My project is a little too big, I have 200k lines of code + 2.8 million lines of code in third party modules I'm using. I'm fixing AutoForm bugs as soon as I'm finding them, however it's a little difficult to see where the bugs are coming from or what is exactly causing the performance issues when the project size is that big, I have to trace and control a lot of things. (I'm the only developer)

I don't have enough time and resources to check if my fixes cause any other bugs or issues for others, this needs to be tested.

Hope we can all help find bugs and issues, fix them together, and benefit from them together.

**Comment by StorytellerCZ** [comment]
Create Autoforms team: https://github.com/orgs/Meteor-Community-Packages/teams/autoforms
And assigned to them the repositories. With this I think this is all that is needed.
