### ISSUE TITLE
Webpage

### ISSUE THREAD

**Issue by StorytellerCZ** [Meteor-Community-Packages/organization#5]
I think sooner or later a crossroad page will be needed. For now, I think a static page served from GitHub will be enough. I would like to use this issue as a discussion point to decide what should be there.

More down the line, I think it would be nice to use something like [Utopian](https://colony.utopian.io/) which could solve a few problems around funding and technical side of things.

**Comment by StorytellerCZ** [comment]
Repository for the website (for now):
https://github.com/Meteor-Community-Packages/website

Domain: meteorjs.community

**Comment by Falkovic1993** [comment]
Hey @StorytellerCZ, 

Would love to help with whatever if you need a couple of extra hands, let me know.

**Comment by StorytellerCZ** [comment]
@Falkovic1993 Any help is welcomed. What is your area of interest?

**Comment by aliogaili** [comment]
Great initiative @StorytellerCZ 

Static website is a great start, I was thinking that it'd be useful to mimic the webpack site a bit. The meteor.com site is positioned more of an enterprise rather than open source project. 

Regarding the name, I had [meteor.js.org](https://js.org/) in mind or meteorjs.org. In terms of features I think the key is to list members, packages and allow them to vote on features. 

But here more potential future ideas:

1. List core community members (people/or companies)
2. Allow voting on next roadmap items with an influencer system
3. Accept donation (that impact the influence points)
4. List core community packages
5. List recommended community resources scatter around the internet
6. The app/organization should be lean and easy to maintain going forward (meaning no need for for podcasts, or anything that takes a lot of manual time) since most of the folks on it will volunteer their time.

Finally, I'll add that there is potential for more generic product to help organize open source communities a bit.

**Comment by aliogaili** [comment]
Even the repo name I think could be made more generic, something like meteororg instead of community packages if we want the long-term vision to have an open organization supporting meteor.

**Comment by StorytellerCZ** [comment]
@aliogaili Thanks for the ideas. Regarding name and heading I think we will stick with this until we can get a bit more off the ground. That is a topic for #1 .
I like the idea of `meteor.js.org`. Though that seems to be only for static GitHub hosted websites, which could limit us in the future.
I will deploy the static placeholder website for now.

**Comment by aliogaili** [comment]
Yes that was my concern with meteor.js.org as well, it seems static only. Although webpack uses it and they seem to have some dynamic features (like voting, auth) going.

**Comment by StorytellerCZ** [comment]
Interesting. Well I just started experimenting with this static site thing, so there is a lot for me to learn. If feasible then I will expand on the current page more.

**Comment by StorytellerCZ** [comment]
Since we now have a dedicated repository for the website, let's move the discussion there.
https://github.com/Meteor-Community-Packages/website
