### ISSUE TITLE
New package for inclusion - aldeed:simple-schema

### ISSUE THREAD

**Issue by jankapunkt** [Meteor-Community-Packages/organization#69]
## Package/project name & description

aldeed:simple schema is the unmaintained Meteor version of `simpl-schema` which is required for Collection2 and aldeed:autoform among others

## Links
* [Atmosphere](https://atmospherejs.com/aldeed/simple-schema)
* [Github repository](https://github.com/longshotlabs/meteor-simple-schema)

## Current status of the project

 * Abandoned (the Meteor package at least, while the npm package is actively maintained)

 ## Reasoning
The Problem is that the npm package dropped all Meteor support with new major version 3! This already caused issues with AutoForm and we should keep focussing to include this package.

The idea is to publish the same versions of the NPM versions as Meteor package but also Include all the dropped Meteor functionality
 
 ## Progress
-  [x] Contacted, https://github.com/longshotlabs/meteor-simple-schema/issues/737
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere
 - [ ] Added to the [community website](https://github.com/Meteor-Community-Packages/website) project listings

**Comment by paulincai** [comment]
When I migrated to simpl-schema 3,  ```userId: { type: String, regEx: SimpleSchema.RegEx.Id },``` is the only thing that bothered me. "SimpleSchema.RegEx.Id" is no longer supported. But ... from the documentation:

"
In earlier releases, the SimpleSchema.RegEx object defined standard regular expressions that you could use as the value for the regEx key. However, many of these were prone to DDoS security risks, causing this package to be flagged by security audit tooling. We no longer include any built-in regular expressions. We encourage you to use a custom function or some other method of validating any strings with complex requirements. **_If necessary, you can look back at the code for previous SimpleSchema releases and copy specific built-in regular expressions into your codebase._**
"
I guess the missing bits in Meteor can be written as functions so that the Meteor packages can then depend on the latests versions of simpl-schema.

**Comment by minhna** [comment]
is there any problem if we use this package without using `SimpleSchema.RegEx`?

**Comment by jankapunkt** [comment]
AutoForm and Collection2 max rely on the regex and Implementations of users may, too. We could easily provide the RegEx as before by simply adding it to the export or by providing an extra package but the tracker integration is not that trivial

**Comment by jankapunkt** [comment]
The tracker integration is especially necessary if you have reactive translations for your schema validation. Also the message box is removed so if your implementation did heavily rely on simple schema then there is a lot more to refactor than just regexes.

**Comment by StorytellerCZ** [comment]
Yes let's try to get simple-schema package and if we can't we'll fork.

**Comment by JanMP** [comment]
I would like to volunteer on this one

**Comment by aldeed** [comment]
Hey all, getting caught up. I'm okay with transferring the meteor package but it also may make sense to just add support for reactivity and other things directly in the packages that need it (e.g. autoform). Depends on how many layers of packages you want to keep track of.

**Comment by StorytellerCZ** [comment]
I think it is preferable to transfer and for us to make it backward compatible as there are many more packages that expect that behavior and some of them won't be receiving any updates.

**Comment by aldeed** [comment]
Transferred repo and added Atmosphere maintainer.

**Comment by StorytellerCZ** [comment]
@aldeed Thank you!
