### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by StorytellerCZ** [Meteor-Community-Packages/organization#9]
I was wondering what are people's thoughts on translating docs, guide, and tutorials into other languages. I think that might increase the accessibility around the world.

Personally, I can translate into Czech at this time.

**Comment by KoenLav** [comment]
I think, as a community which isn't all that active (IMHO), we should try to do a small number of things good, rather than a lot of things half.

Translating docs will definitely help any framework/community, but I think there are more important things left to do (getting the hype back on, maintaining packages, working on a slimmer core, etc).

**Comment by SimonSimCity** [comment]
... and keeping the docs up to date. There are still parts of the "Meteor Guide" which (to me) are outdated or would need a new description for a "best practice". At least when I started with Meteor (3y back) the docs contained a lot of outdated "best practices" which quickly proved to be misleading.

Nothing against getting things translated, but I agree with @KoenLav that we shouldn't make it a focus before other things are in place.

On the other side, I also see less and less frameworks taking an effort on translation in general.

**Comment by jankapunkt** [comment]
> getting the hype back on

I think the biggest recent argument pro Meteor is that it has survived the hype :-)

> On the other side, I also see less and less frameworks taking an effort on translation in general.

I think they realized,, that since programming languages above machine code are mainly written with English semantics, the majority of developers is or becomes very familiar with English and keep their docs mostly in this language.

When it comes to tight resources this is IMO the way to go.

**Comment by StorytellerCZ** [comment]
Closing this for now. Hopefully we will reach a point in the future when I can re-open.
